// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVlmUsBVUR5R9WtW1dui07nI1GvRZ9jNc',
    appId: '1:886688174860:web:75499f49540da8b3ef6f29',
    messagingSenderId: '886688174860',
    projectId: 'payflow-14c69',
    authDomain: 'payflow-14c69.firebaseapp.com',
    storageBucket: 'payflow-14c69.appspot.com',
    measurementId: 'G-RE1YHD2C7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8MALcLrN_e7PhTjG2OOPeO5YLrc9hdfU',
    appId: '1:886688174860:android:b95c4fec8cb85a41ef6f29',
    messagingSenderId: '886688174860',
    projectId: 'payflow-14c69',
    storageBucket: 'payflow-14c69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwtrPXA9KLYgu1tTnUOkgMMh-Ouw6Pe8Q',
    appId: '1:886688174860:ios:5d9c179cec0f428aef6f29',
    messagingSenderId: '886688174860',
    projectId: 'payflow-14c69',
    storageBucket: 'payflow-14c69.appspot.com',
    androidClientId: '886688174860-on3tdc4v3ol3b0ept245goi2qesmrp3p.apps.googleusercontent.com',
    iosClientId: '886688174860-igoj3ia3mkbdfc027todj6shgittnueb.apps.googleusercontent.com',
    iosBundleId: 'com.example.payflow',
  );
}
